#!/bin/bash

#Submit this script with: sbatch thefilename

#SBATCH -p defq
#SBATCH --ntasks=1   # number of processor cores (i.e. tasks)
#SBATCH --mem-per-cpu=5G   # memory per CPU core
#SBATCH -J "{fn}"   # job name

# LOAD MODULES, INSERT CODE, AND RUN YOUR PROGRAMS HERE

python3 -m tdse.main convergence_test/{fn}.dipf
